#if !defined(MOBAGAMEELEMENTSENUM_H)
#define MOBAGAMEELEMENTSENUM_H

enum GameElementNames
{
	gameElementHUD,
	gameElementPlayerAvatar,
	gameElementItemIcon,
	gameElementBuffIcon,
	gameElementItemTooltipBackground,
	gameElementAbilityTooltipBackground,
	gameElementBuffTooltipBackground,
	gameElementTradeInventoryLabel,
	gameElementTradeMenuBackground,
	gameElementTradeMenuTitle,
	gameElementConfirmTrade,
	gameElementHealthBar,
	gameElementAbility1,
	gameElementAbility2,
	gameElementAbility3,
	gameElementAbility4,
	gameElementAbilityCustom1,
	gameElementAbilityCustom2,
	gameElementAbilityRecall,
	gameElementAbilitySleep,
	gameElementCharacterStatLabelMoveSpeed,
	gameElementCharacterStatLabelRange,
	gameElementCharacterStatLabelAttackSpeed,
	gameElementCharacterStatLabelPhysical,
	gameElementCharacterStatLabelCatVoodoo,
	gameElementCharacterStatLabelArmor,
	gameElementCharacterStatLabelCatVoodooResist,
	gameElementCharacterStatLabelHPRegen,
	gameElementCharacterStatLabelHealth,
	gameElementCharacterStatLabelMaxHealth,
	gameElementGameInfoPanel,
	gameElementInfoAvatar0,
	gameElementInfoAvatar1,
	gameElementInfoAvatar2,
	gameElementInfoAvatar3,
	gameElementInfoAvatar4,
	gameElementInfoAvatar5,
	gameElementInfoAvatar6,
	gameElementInfoAvatar7,
	gameElementInfoAvatar8,
	gameElementInfoAvatar9,
	gameElementInv0,
	gameElementInv1,
	gameElementInv2,
	gameElementInv3,
	gameElementInv4,
	gameElementInv5,
	gameElementInv6,
	gameElementInv7,
	gameElementInv8,
	gameElementInv9,
	gameElementStatBackground,
	gameElementStatVerticalStats,

	gameElementCount
};

#endif